#include "euler.h"
#include "math/fibonacci.h"
#include "util/filter.h"
#include "util/takewhile.h"
#include "util/predicates.h"
#include "util/sum.h"
using namespace util;
using namespace math;

// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
//      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

std::string euler002()
{
    return std::to_string(
        sum(filter( takewhile(fibonacci(1, 2), less<4000000>()), even() ))
    );
}

static bool reg_ = euler::set("2", euler002);
